### ISSUE TITLE
convertLigParGen.py issue

### ISSUE THREAD

**Issue by rnieman** [mccg-pas/group-wiki#3]
Hello,

We are wanting to use the OPLS-AA force field with LAMMPS and your utility was recommended to us. I am following the tutorial from:
https://longkunxuluke.github.io/posts/2020/11/blog-post-4/
with MeOH and a hydrocarbon. I generate the files for both from the LibParGen server, but when I execute convertLibParGen.py, I get the following error:

python convertLigParGen.py -l 2_DF9EF0.lmp -g 2_DF9EF0.top -o out.ff
Traceback (most recent call last):
  File "convertLigParGen.py", line 358, in <module>
    convertToIlFF(itpPath=args.gromacs, outputPath=args.output, lammpsTopology=args.lammps)
  File "convertLigParGen.py", line 331, in convertToIlFF
    tempXYZ = fetchXYZ(lammpsTopology, atomsList)
  File "convertLigParGen.py", line 285, in fetchXYZ
    finalLine = atomName + atomXYZ
UnboundLocalError: local variable 'atomName' referenced before assignment

My python skills are not strong, so while I think I understand this problem, I don't know how to solve it. I have attached the input files I use. Thank you for any help!

[input.zip](https://github.com/mccg-pas/group-wiki/files/9768149/input.zip)

Best regards,
Reed

**Comment by rnieman** [comment]
The instructions are slightly misleading. The top file is not *.top, but *.itp. Making this replacement, the python script works now.

Thank you.

**Comment by mrobinson-hub** [comment]
Hi Reed,

I'm glad you solved the issue! My apologies for the confusion here - when I wrote the script, it was the .itp file that was required. A couple of year ago, an update to LigParGen changed the filenames around and it was the .top file that was required - it sounds like that has changed again. I'm in the midst of writing my thesis and shouldn't spend too much time investigating this, so for now I'll just put a note in the instructions that it will be one of those two file types.

Thanks for bringing this to my attention,

Regards,
Michael
